name: Previsão Diária Bitcoin

# GATILHOS (Quando deve rodar?)
on:
  schedule:
    # Roda todos os dias às 09:00 UTC
    - cron: '0 9 * * *'
  # Botão manual para testar agora
  workflow_dispatch:

jobs:
  run-prediction:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixar o teu código
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      # 2. Instalar Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Instalar bibliotecas
      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install numpy<2.0.0 pandas==2.2.2 pandas_ta vaderSentiment gnews tensorflow scikit-learn requests

      # 4. Rodar a IA
      - name: Executar IA de Previsão
        run: python scripts/prever_criptoia.py
